### ISSUE TITLE
Skippind during streaming

### ISSUE THREAD

**Issue by 0x09AF** [idMysteries/mpv-skip-silence#2]
Amazing script! Thanks a lot for your work!
I noticed it doesn't work during `mpv` streaming a video, even when the video is completely cached.
Are there plans to implement skipping silence during streaming?

It may be a simple fix. Looking at the `mpv` output it tries to download the video it's already streaming, as if we ran the `auto-edit` script separately.

**Comment by idMysteries** [comment]
To skip silence in a video, you need a video file. I can implement silence skipping for streams, but it won't work as well.
